<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment|glob|magic|root-XML|alias|sub-class-of)*>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA #IMPLIED>

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML
  	namespaceURI CDATA #REQUIRED
	localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias
  	type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of
  	type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/andrew-inset">
    <comment>Andrew Toolkit inset</comment>
    <comment xml:lang="az">Andrew Toolkit sənədi</comment>
    <comment xml:lang="cy">Mewnosodiad Andrew Toolkit</comment>
    <comment xml:lang="fi">Andrew Toolkit -osio</comment>
    <comment xml:lang="fr">ajout Andrew Toolkit</comment>
    <comment xml:lang="hu">Andrew Toolkit inset</comment>
    <comment xml:lang="nn">Andrew Toolkit innsats</comment>
    <comment xml:lang="no">Andrew verktøysett insett</comment>
    <comment xml:lang="sr">Andrew додатаг групе алата</comment>
    <comment xml:lang="sv">Andrew-verktygssamling insatt</comment>
    <glob pattern="*.ez" />
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator document</comment>
    <comment xml:lang="no">Adobe Illustrator-dokument</comment>
    <comment xml:lang="sv">Adobe Illustrator-dokument</comment>
    <glob pattern="*.ai" />
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <comment xml:lang="az">Macintosh BinHex-kodlanmış fayl</comment>
    <comment xml:lang="cy">Ffeil BinHex-amgodwyd Macintosh</comment>
    <comment xml:lang="fi">Macintosh BinHex -koodattu tiedosto</comment>
    <comment xml:lang="fr">fichier encode Macintosh BinHex</comment>
    <comment xml:lang="hu">Macintosh BinHex kódolású fájl</comment>
    <comment xml:lang="nl">Macintosh BinHex-gecodeerd bestand</comment>
    <comment xml:lang="nn">Macintosh BinHex-koda fil</comment>
    <comment xml:lang="no">Macintosh BinHe-kodet arkiv</comment>
    <comment xml:lang="sr">Мекинтош BinHex-encoded датотека</comment>
    <comment xml:lang="sv">Macintosh BinHex-kodad fil</comment>
    <magic priority="50">
      <match offset="11" type="string" value="must be converted with BinHex" />
    </magic>
  </mime-type>
  <mime-type type="application/msword">
    <comment>Microsoft Word document</comment>
    <comment xml:lang="az">Microsoft Word sənədi</comment>
    <comment xml:lang="cy">Dogfen Miscrosoft Word</comment>
    <comment xml:lang="fi">Microsoft Word -asiakirja</comment>
    <comment xml:lang="fr">document Microsoft Word</comment>
    <comment xml:lang="hu">Microsoft Word-dokumentum</comment>
    <comment xml:lang="nl">Microsoft Word document</comment>
    <comment xml:lang="nn">Microsoft Word-dokument</comment>
    <comment xml:lang="no">Microsoft Word dokument</comment>
    <comment xml:lang="sr">Микрософт Word документ</comment>
    <comment xml:lang="sv">Microsoft Word-dokument</comment>
    <magic priority="50">
      <match offset="0" type="string" value="\x31\xbe\x00\x00" />
      <match offset="0" type="string" value="PO^Q`" />
      <match offset="0" type="string" value="\376\067\0\043" />
      <match offset="0" type="string" value="\333\245-\0\0\0" />
      <match offset="2080" type="string" value="Microsoft Word 6.0 Document" />
      <match offset="2112" type="string" value="Microsoft Word document data" />
    </magic>
    <glob pattern="*.doc" />
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>unknown</comment>
    <comment xml:lang="no">ukjent</comment>
    <magic priority="50">
      <match offset="0" type="string" value="\037\036" />
      <match offset="0" type="host16" value="017437" />
      <match offset="0" type="host16" value="0x1fff" />
      <match offset="0" type="string" value="\377\037" />
      <match offset="0" type="host16" value="0145405" />
    </magic>
    <glob pattern="*.bin" />
  </mime-type>
  <mime-type type="application/oda">
    <comment>ODA document</comment>
    <comment xml:lang="az">ODA sənədi</comment>
    <comment xml:lang="cy">Dogfen ODA</comment>
    <comment xml:lang="fi">ODA-asiakirja</comment>
    <comment xml:lang="fr">document ODA</comment>
    <comment xml:lang="hu">ODA-dokumentum</comment>
    <comment xml:lang="nl">ODA document</comment>
    <comment xml:lang="nn">ODA-dokument</comment>
    <comment xml:lang="no">ODA-dokument</comment>
    <comment xml:lang="sr">ODA документ</comment>
    <comment xml:lang="sv">ODA-dokument</comment>
    <glob pattern="*.oda" />
  </mime-type>
  <mime-type type="application/pdf">
    <comment>PDF document</comment>
    <comment xml:lang="cy">Dogfen PDF</comment>
    <comment xml:lang="nn">PDF-dokument</comment>
    <comment xml:lang="no">PDF-dokument</comment>
    <comment xml:lang="sr">PDF документ</comment>
    <comment xml:lang="sv">PDF-dokument</comment>
    <magic priority="50">
      <match offset="0" type="string" value="%PDF-" />
    </magic>
    <glob pattern="*.pdf" />
  </mime-type>
  <mime-type type="application/pgp">
    <comment>PGP message</comment>
    <comment xml:lang="az">PGP ismarışı</comment>
    <comment xml:lang="cy">Neges PGP</comment>
    <comment xml:lang="fi">PGP-viesti</comment>
    <comment xml:lang="fr">message PGP</comment>
    <comment xml:lang="hu">PGP-üzenet</comment>
    <comment xml:lang="nl">PGP bericht</comment>
    <comment xml:lang="nn">PGP-melding</comment>
    <comment xml:lang="no">PGP-melding</comment>
    <comment xml:lang="sr">PGP порука</comment>
    <comment xml:lang="sv">PGP-meddelande</comment>
    <glob pattern="*.pgp" />
  </mime-type>
  <mime-type type="application/pgp-encrypted">
    <comment>PGP/MIME-encrypted message header</comment>
    <comment xml:lang="no">PGP/MIME-kryptert meldingshode</comment>
  </mime-type>
  <mime-type type="application/pgp-keys">
    <comment>PGP keys</comment>
    <comment xml:lang="az">PGP açarları</comment>
    <comment xml:lang="cy">Allweddi PGP</comment>
    <comment xml:lang="fi">PGP-avainrengas</comment>
    <comment xml:lang="fr">clés PGP</comment>
    <comment xml:lang="hu">PGP-kulcs</comment>
    <comment xml:lang="nl">PGP sleutels</comment>
    <comment xml:lang="nn">PGP-nøkler</comment>
    <comment xml:lang="no">PGP-nøkler</comment>
    <comment xml:lang="sr">PGP кључ</comment>
    <comment xml:lang="sv">PGP-nycklar</comment>
  </mime-type>
  <mime-type type="application/pgp-signature">
    <comment>detached OpenPGP signature</comment>
    <comment xml:lang="no">frakoblet OpenPGP-signatur</comment>
  </mime-type>
  <mime-type type="application/pkcs7-mime">
    <comment>S/MIME file</comment>
    <comment xml:lang="az">S/MIME faylı</comment>
    <comment xml:lang="cy">Ffeil S/MIME</comment>
    <comment xml:lang="fi">S/MIME-tiedosto</comment>
    <comment xml:lang="fr">fichier S/MIME</comment>
    <comment xml:lang="hu">S/MIME-fájl</comment>
    <comment xml:lang="nl">S/MIME bestand</comment>
    <comment xml:lang="nn">S/MIME-fil</comment>
    <comment xml:lang="no">S/MIME-fil</comment>
    <comment xml:lang="sr">S/MIME датотека</comment>
    <comment xml:lang="sv">S/MIME-fil</comment>
  </mime-type>
  <mime-type type="application/pkcs7-signature">
    <comment>detached S/MIME signature</comment>
    <comment xml:lang="no">frakoblet S/MIME-signatur</comment>
    <glob pattern="*.p7s" />
  </mime-type>
  <mime-type type="application/postscript">
    <comment>PostScript document</comment>
    <comment xml:lang="no">PostScript-dokument</comment>
    <comment xml:lang="sv">PostScript-dokument</comment>
    <magic priority="50">
      <match offset="0" type="string" value="\004%!" />
      <match offset="0" type="string" value="%!" />
    </magic>
    <glob pattern="*.ps" />
  </mime-type>
  <mime-type type="application/rtf">
    <comment>Rich Text Format</comment>
    <comment xml:lang="az">Zəngin Mətn Formatı</comment>
    <comment xml:lang="cy">Dogfen Testun Gyfoethog</comment>
    <comment xml:lang="fi">RTF-asiakirja</comment>
    <comment xml:lang="fr">Rich Text Format</comment>
    <comment xml:lang="hu">RTF-fájl</comment>
    <comment xml:lang="nl">Rijke Tekst Formaat</comment>
    <comment xml:lang="nn">Rik tekst-dokument</comment>
    <comment xml:lang="no">Rik tekst-format</comment>
    <comment xml:lang="sr">Обогаћени текстуални запис (RTF)</comment>
    <comment xml:lang="sv">Rikt textdokument</comment>
    <magic priority="50">
      <match offset="0" type="string" value="{\\rtf" />
    </magic>
    <glob pattern="*.rtf" />
  </mime-type>
  <mime-type type="application/smil">
    <comment>Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="az">Sinxronlaşdırılmış Multemediya İnteqrasiya Dili</comment>
    <comment xml:lang="cy">Iaith Integreiddio Aml-Gyfrwng wedi ei Chydweddu</comment>
    <comment xml:lang="fi">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="fr">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="hu">Szinkronizált multimédiaintegrációs nyelv</comment>
    <comment xml:lang="nl">Gesynchroniseerde multimedia integratie taal</comment>
    <comment xml:lang="nn">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="sr">Синхронизовани језик за интеграцију мултимедије (SMIL)</comment>
    <comment xml:lang="sv">Språk för synkroniserad multimediaintegration</comment>
    <glob pattern="*.smil" />
    <glob pattern="*.smi" />
    <glob pattern="*.sml" />
  </mime-type>
  <mime-type type="application/vnd.corel-draw">
    <comment>Corel Draw drawing</comment>
    <comment xml:lang="az">Corel Draw çəkimi</comment>
    <comment xml:lang="cy">Darlun Corel Draw</comment>
    <comment xml:lang="fi">Corel Draw -piirros</comment>
    <comment xml:lang="fr">dessin Corel Draw</comment>
    <comment xml:lang="hu">Corel Draw-rajz</comment>
    <comment xml:lang="nl">Corel Draw tekening</comment>
    <comment xml:lang="nn">Corel Draw-teikning</comment>
    <comment xml:lang="no">Corel Draw-tegning</comment>
    <comment xml:lang="sr">Corel Draw цртеж</comment>
    <comment xml:lang="sv">Corel Draw-teckning</comment>
    <magic priority="50">
      <match offset="8" type="string" value="CDR vrsn" />
    </magic>
    <glob pattern="*.cdr" />
  </mime-type>
  <mime-type type="application/vnd.hp-hpgl">
    <comment>HP Graphics Language (plotter)</comment>
    <glob pattern="*.hpgl" />
  </mime-type>
  <mime-type type="application/vnd.hp-pcl">
    <comment>HP Printer Control Language file</comment>
    <glob pattern="*.pcl" />
  </mime-type>
  <mime-type type="application/vnd.lotus-1-2-3">
    <comment>Lotus 1-2-3 spreadsheet</comment>
    <comment xml:lang="az">Lotus 1-2-3 hesab cədvəli</comment>
    <comment xml:lang="cy">Taenlen Lotus 1-2-3</comment>
    <comment xml:lang="fi">Lotus 1-2-3 -taulukko</comment>
    <comment xml:lang="fr">chiffrier Lotus 1-2-3</comment>
    <comment xml:lang="hu">Lotus 1-2-3-munkafüzet</comment>
    <comment xml:lang="nl">Lotus 1-2-3 spreadsheet</comment>
    <comment xml:lang="nn">Lotus 1-2-3 rekneark</comment>
    <comment xml:lang="no">Lotus 1-2-3 regneark</comment>
    <comment xml:lang="sr">Lotus 1-2-3 табеларни прорачун</comment>
    <comment xml:lang="sv">Lotus 1-2-3-kalkylblad</comment>
    <magic priority="50">
      <match offset="0" type="string" value="\x00\x00\x02\x00" />
    </magic>
    <glob pattern="*.123" />
    <glob pattern="*.wk1" />
    <glob pattern="*.wk3" />
    <glob pattern="*.wk4" />
    <glob pattern="*.wks" />
  </mime-type>
  <mime-type type="application/vnd.ms-excel">
    <comment>Microsoft Excel spreadsheet</comment>
    <comment xml:lang="az">Microsoft Excel hesab cədvəli</comment>
    <comment xml:lang="cy">Taenlen Microsoft Excel</comment>
    <comment xml:lang="fi">Microsoft Excel -taulukko</comment>
    <comment xml:lang="fr">chiffrier Microsoft Excel</comment>
    <comment xml:lang="hu">Microsoft Excel-munkafüzet</comment>
    <comment xml:lang="nl">Microsoft Excel spreadsheet</comment>
    <comment xml:lang="nn">Microsoft Excel reikneark</comment>
    <comment xml:lang="no">Microsoft Excel regneark</comment>
    <comment xml:lang="sr">Микрософт Ексел табеларни прорачун</comment>
    <comment xml:lang="sv">Microsoft Excel-kalkylblad</comment>
    <magic priority="50">
      <match offset="2080" type="string" value="Microsoft Excel 5.0 Worksheet" />
    </magic>
    <glob pattern="*.xls" />
    <glob pattern="*.xlc" />
    <glob pattern="*.xll" />
    <glob pattern="*.xlm" />
    <glob pattern="*.xlw" />
    <glob pattern="*.xla" />
    <glob pattern="*.xlt" />
    <glob pattern="*.xld" />
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint">
    <comment>Microsoft PowerPoint presentation</comment>
    <comment xml:lang="no">Microsoft PowerPoint-presentasjon</comment>
    <glob pattern="*.ppz" />
    <glob pattern="*.ppt" />
    <glob pattern="*.pps" />
    <glob pattern="*.pot" />
  </mime-type>
  <mime-type type="application/vnd.ms-word">
    <comment>Microsoft Word document</comment>
    <comment xml:lang="az">Microsoft Word sənədi</comment>
    <comment xml:lang="cy">Dogfen Miscrosoft Word</comment>
    <comment xml:lang="fi">Microsoft Word -asiakirja</comment>
    <comment xml:lang="fr">document Microsoft Word</comment>
    <comment xml:lang="hu">Microsoft Word-dokumentum</comment>
    <comment xml:lang="nl">Microsoft Word document</comment>
    <comment xml:lang="nn">Microsoft Word-dokument</comment>
    <comment xml:lang="no">Microsoft Word dokument</comment>
    <comment xml:lang="sr">Микрософт Word документ</comment>
    <comment xml:lang="sv">Microsoft Word-dokument</comment>
  </mime-type>
  <mime-type type="application/vnd.palm">
    <comment>Palmpilot database/document</comment>
    <glob pattern="*.pdb" />
  </mime-type>
  <mime-type type="application/vnd.rn-realmedia">
    <comment>RealAudio/Video document</comment>
    <comment xml:lang="az">RealAudio/Video sənədi</comment>
    <comment xml:lang="cy">Dogfen RealAudio neu RealVideo</comment>
    <comment xml:lang="fi">RealAudio/Video-asiakirja</comment>
    <comment xml:lang="fr">document RealAudio/Video</comment>
    <comment xml:lang="hu">RealAudio/Video-dokumentum</comment>
    <comment xml:lang="nl">RealAudio/Video document</comment>
    <comment xml:lang="nn">RealAudio/Video-dokument</comment>
    <comment xml:lang="no">RealAudio/Video-dokument</comment>
    <comment xml:lang="sr">RealAudio/Video документ</comment>
    <comment xml:lang="sv">RealAudio/Video-dokument</comment>
  </mime-type>
  <mime-type type="application/vnd.stardivision.calc">
    <comment>StarCalc spreadsheet</comment>
    <comment xml:lang="az">StarCalc hesab cədvəli</comment>
    <comment xml:lang="cy">Taenlen StarCalc</comment>
    <comment xml:lang="fi">StarCalc-taulukko</comment>
    <comment xml:lang="fr">chiffier StarCalc</comment>
    <comment xml:lang="hu">StarCalc-munkafüzet</comment>
    <comment xml:lang="nl">StarCalc spreadsheet</comment>
    <comment xml:lang="nn">StarCalc-rekneark</comment>
    <comment xml:lang="no">StarCalc-regneark</comment>
    <comment xml:lang="sr">StarCalc табеларни прорачун</comment>
    <comment xml:lang="sv">StarCalc-kalkylblad</comment>
    <glob pattern="*.sdc" />
  </mime-type>
  <mime-type type="application/vnd.stardivision.chart">
    <comment>StarChart chart</comment>
    <comment xml:lang="az">StarChart cədvəli</comment>
    <comment xml:lang="cy">Siart StarChart</comment>
    <comment xml:lang="fi">StarChart-kaavio</comment>
    <comment xml:lang="fr">graphique StarChart</comment>
    <comment xml:lang="hu">StarChart-grafikon</comment>
    <comment xml:lang="nl">StarChart grafiek</comment>
    <comment xml:lang="nn">StarChart-graf</comment>
    <comment xml:lang="no">StarChart graf</comment>
    <comment xml:lang="sr">StarChart графикон</comment>
    <comment xml:lang="sv">StarChart-diagram</comment>
    <glob pattern="*.sds" />
  </mime-type>
  <mime-type type="application/vnd.stardivision.draw">
    <comment>StarDraw drawing</comment>
    <comment xml:lang="az">StarDraw çəkimi</comment>
    <comment xml:lang="cy">Darlun StarDraw</comment>
    <comment xml:lang="fi">StarDraw-piirros</comment>
    <comment xml:lang="fr">dessin StarDraw</comment>
    <comment xml:lang="hu">StarDraw-rajz</comment>
    <comment xml:lang="nl">StarDraw tekening</comment>
    <comment xml:lang="nn">StarDraw-teikning</comment>
    <comment xml:lang="no">StarDraw tegning</comment>
    <comment xml:lang="sr">StarDraw drawing</comment>
    <comment xml:lang="sv">StarDraw-teckning</comment>
    <glob pattern="*.sda" />
  </mime-type>
  <mime-type type="application/vnd.stardivision.impress">
    <comment>StarImpress presentation</comment>
    <comment xml:lang="az">StarImpress təqdimatı</comment>
    <comment xml:lang="cy">Cyflwyniad StarImpress</comment>
    <comment xml:lang="fi">StarImpress-esitys</comment>
    <comment xml:lang="fr">présentation StarImpress</comment>
    <comment xml:lang="hu">StarImpress-bemutató</comment>
    <comment xml:lang="nl">StarImpress presentatie</comment>
    <comment xml:lang="nn">StarImpress-presentasjon</comment>
    <comment xml:lang="no">StarImpress-presentasjon</comment>
    <comment xml:lang="sr">StarImpress презентација</comment>
    <comment xml:lang="sv">StarImpress-presentation</comment>
    <glob pattern="*.sdd" />
    <glob pattern="*.sdp" />
  </mime-type>
  <mime-type type="application/vnd.stardivision.mail">
    <comment>StarMail email</comment>
    <comment xml:lang="no">StarMail-melding</comment>
    <glob pattern="*.smd" />
  </mime-type>
  <mime-type type="application/vnd.stardivision.math">
    <comment>StarMath formula</comment>
    <comment xml:lang="no">StarMath-formel</comment>
    <glob pattern="*.smf" />
  </mime-type>
  <mime-type type="application/vnd.stardivision.writer">
    <comment>StarWriter document</comment>
    <comment xml:lang="az">StarWriter sənədi</comment>
    <comment xml:lang="cy">Dogfen StarWriter</comment>
    <comment xml:lang="fi">StarWriter-asiakirja</comment>
    <comment xml:lang="fr">document StarWriter</comment>
    <comment xml:lang="hu">StarWriter-dokumentum</comment>
    <comment xml:lang="nl">StarWriter document</comment>
    <comment xml:lang="nn">StarWriter document</comment>
    <comment xml:lang="no">StarWriter-dokument</comment>
    <comment xml:lang="sr">StarWriter документ</comment>
    <comment xml:lang="sv">StarWriter-dokument</comment>
    <glob pattern="*.sdw" />
    <glob pattern="*.vor" />
    <glob pattern="*.sgl" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc">
    <comment>OpenOffice.org Calc spreadsheet</comment>
    <comment xml:lang="no">OpenOffice.org Calc-regneark</comment>
    <glob pattern="*.sxc" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc.template">
    <comment>OpenOffice.org Calc spreadsheet template</comment>
    <comment xml:lang="no">OpenOffice.org Calc-regnearkmal</comment>
    <glob pattern="*.stc" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw">
    <comment>OpenOffice.org Draw drawing</comment>
    <comment xml:lang="no">OpenOffice.org Draw-tegning</comment>
    <glob pattern="*.sxd" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw.template">
    <comment>OpenOffice.org Draw drawing template</comment>
    <comment xml:lang="no">OpenOffice.org Draw-tegningsmal</comment>
    <glob pattern="*.std" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress">
    <comment>OpenOffice.org Impress presentation</comment>
    <comment xml:lang="no">OpenOffice.org Impress-presentasjon</comment>
    <comment xml:lang="sv">OpenOffice.org Impress-presentation</comment>
    <glob pattern="*.sxi" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress.template">
    <comment>OpenOffice.org Impress presentation template</comment>
    <comment xml:lang="no">OpenOffice.org Impress-presentasjonsmal</comment>
    <comment xml:lang="sv">OpenOffice.org Impress-presentationsmall</comment>
    <glob pattern="*.sti" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.math">
    <comment>OpenOffice.org Math formula</comment>
    <comment xml:lang="no">OpenOffice.org Math-dokument</comment>
    <glob pattern="*.sxm" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer">
    <comment>OpenOffice.org Writer document</comment>
    <comment xml:lang="no">OpenOffice.org Writer-dokument</comment>
    <comment xml:lang="sv">OpenOffice.org Writer-dokument</comment>
    <glob pattern="*.sxw" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.global">
    <comment>OpenOffice.org Writer global document</comment>
    <comment xml:lang="no">Globalt OpenOffice.org Writer-dokument</comment>
    <comment xml:lang="sv">OpenOffice.org Writer-globaldokument</comment>
    <glob pattern="*.sxg" />
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.template">
    <comment>OpenOffice.org Writer document template</comment>
    <comment xml:lang="no">OpenOffice.org Writer-dokumentmal</comment>
    <glob pattern="*.stw" />
  </mime-type>
  <mime-type type="application/wordperfect">
    <comment>WordPerfect document</comment>
    <comment xml:lang="az">WordPerfect sənədi</comment>
    <comment xml:lang="cy">Dogfen WordPerfect</comment>
    <comment xml:lang="fi">WordPerfect-asiakirja</comment>
    <comment xml:lang="fr">document WordPerfect</comment>
    <comment xml:lang="hu">WordPerfect-dokumentum</comment>
    <comment xml:lang="nl">WordPerfect document</comment>
    <comment xml:lang="nn">WordPerfect-dokument</comment>
    <comment xml:lang="no">WordPerfect-dokument</comment>
    <comment xml:lang="sr">WordPerfect документ</comment>
    <comment xml:lang="sv">WordPerfect-dokument</comment>
    <magic priority="50">
      <match offset="1" type="string" value="WPC" />
      
    </magic>
    <glob pattern="*.wpd" />
  </mime-type>
  <mime-type type="application/x-xbel">
    <comment>XBEL bookmarks</comment>
    <comment xml:lang="no">XBEL-bokmerker</comment>
    <magic priority="50">
      <match offset="0:64" type="string" value="&lt;!DOCTYPE\ xbel" />
    </magic>
    <glob pattern="*.xbel" />
  </mime-type>
  <mime-type type="application/x-abiword">
    <comment>AbiWord document</comment>
    <comment xml:lang="no">AbiWord-dokument</comment>
    <comment xml:lang="sv">AbiWord-dokument</comment>
    <magic priority="50">
      <match offset="0:64" type="string" value="&lt;abiword" />
      <match offset="0:64" type="string" value="&lt;!DOCTYPE abiword" />
    </magic>
    <glob pattern="*.abw" />
    <glob pattern="*.abw.gz" />
    <glob pattern="*.zabw" />
  </mime-type>
  <mime-type type="application/x-amipro">
    <comment>Lotus AmiPro document</comment>
    <comment xml:lang="az">Lotus AmiPro sənədi</comment>
    <comment xml:lang="cy">Dogfen Lotus AmiPro</comment>
    <comment xml:lang="fi">Lotus AmiPro -asiakirja</comment>
    <comment xml:lang="fr">document Lotus AmiPro</comment>
    <comment xml:lang="hu">Lotus AmiPro-dokumentum</comment>
    <comment xml:lang="nl">Lotus AmiPro document</comment>
    <comment xml:lang="nn">Lotus AmiPro-dokument</comment>
    <comment xml:lang="no">Lotus AmiPro-dokument</comment>
    <comment xml:lang="sr">Лотус АмиПро документ</comment>
    <comment xml:lang="sv">Lotus AmiPro-dokument</comment>
    <glob pattern="*.sam" />
  </mime-type>
  <mime-type type="application/x-applix-spreadsheet">
    <comment>Applix Spreadsheets spreadsheet</comment>
    <comment xml:lang="no">Applix Spreadsheets-regneark</comment>
    <magic priority="50">
      <match offset="0" type="string" value="*BEGIN SPREADSHEETS" />
      <match offset="0" type="string" value="*BEGIN">
        <match offset="7" type="string" value="SPREADSHEETS" />
      </match>
    </magic>
    <glob pattern="*.as" />
  </mime-type>
  <mime-type type="application/x-applix-word">
    <comment>Applix Words document</comment>
    <comment xml:lang="az">Applix Words sənədi</comment>
    <comment xml:lang="cy">Dogfen Applix Words</comment>
    <comment xml:lang="fi">Applix Words -asiakirja</comment>
    <comment xml:lang="fr">document Applix Words</comment>
    <comment xml:lang="hu">Applix Words-dokumentum</comment>
    <comment xml:lang="nl">Applix Words document</comment>
    <comment xml:lang="nn">Applix Words dokument</comment>
    <comment xml:lang="no">Applix Words-dokument</comment>
    <comment xml:lang="sr">Applix Words документ</comment>
    <comment xml:lang="sv">Applix Words-dokument</comment>
    <magic priority="50">
      <match offset="0" type="string" value="*BEGIN">
        <match offset="7" type="string" value="WORDS" />
      </match>
    </magic>
    <glob pattern="*.aw" />
  </mime-type>
  <mime-type type="application/x-arc">
    <magic priority="50">
      <match mask="0x8080ffff" offset="0" type="little32" value="0x0000081a" />
      <match mask="0x8080ffff" offset="0" type="little32" value="0x0000091a" />
      <match mask="0x8080ffff" offset="0" type="little32" value="0x0000021a" />
      <match mask="0x8080ffff" offset="0" type="little32" value="0x0000031a" />
      <match mask="0x8080ffff" offset="0" type="little32" value="0x0000041a" />
      <match mask="0x8080ffff" offset="0" type="little32" value="0x0000061a" />
    </magic>
  </mime-type>
  <mime-type type="application/x-archive">
    <comment>AR archive</comment>
    <comment xml:lang="no">AR-arkiv</comment>
    <magic priority="45">
      <match offset="0" type="string" value="&lt;ar&gt;" />
      <match offset="0" type="string" value="!&lt;arch&gt;" />
    </magic>
    <glob pattern="*.a" />
  </mime-type>
  <mime-type type="application/x-arj">
    <comment>ARJ archive</comment>
    <comment xml:lang="az">ARJ arxivi</comment>
    <comment xml:lang="cy">Archif ARJ</comment>
    <comment xml:lang="fi">ARJ-arkisto</comment>
    <comment xml:lang="fr">archive ARJ</comment>
    <comment xml:lang="hu">ARJ-archívum</comment>
    <comment xml:lang="nl">ARJ archief</comment>
    <comment xml:lang="nn">ARJ-arkiv</comment>
    <comment xml:lang="no">ARJ-arkiv</comment>
    <comment xml:lang="sr">ARJ архива</comment>
    <comment xml:lang="sv">ARJ-arkiv</comment>
    <magic priority="50">
      <match offset="0" type="little16" value="0xea60" />
    </magic>
    <glob pattern="*.arj" />
  </mime-type>
  <mime-type type="application/x-asp">
    <comment>active server page</comment>
    <comment xml:lang="az">active server page sənədi</comment>
    <comment xml:lang="cy">tudalen ASP</comment>
    <comment xml:lang="fi">aktiivinen palvelinsivu</comment>
    <comment xml:lang="fr">page active du serveur</comment>
    <comment xml:lang="hu">ASP (active server page)</comment>
    <comment xml:lang="nl">actieve server pagina</comment>
    <comment xml:lang="nn">active server page</comment>
    <comment xml:lang="no">active server page</comment>
    <comment xml:lang="sr">Активна серверска страна</comment>
    <comment xml:lang="sv">aktiv serversida</comment>
    <glob pattern="*.asp" />
  </mime-type>
  <mime-type type="application/x-awk">
    <comment>AWK script</comment>
    <comment xml:lang="az">AWK skripti</comment>
    <comment xml:lang="cy">Sgript AWK</comment>
    <comment xml:lang="fi">AWK-skripti</comment>
    <comment xml:lang="fr">script AWK</comment>
    <comment xml:lang="hu">AWK-szkript</comment>
    <comment xml:lang="nl">AWK script</comment>
    <comment xml:lang="nn">WAK-skript</comment>
    <comment xml:lang="no">AWK-skript</comment>
    <comment xml:lang="sr">AWK скрипта</comment>
    <comment xml:lang="sv">AWK-skript</comment>
    <magic priority="50">
      <match offset="0" type="string" value="#!/bin/gawk" />
      <match offset="0" type="string" value="#! /bin/gawk" />
      <match offset="0" type="string" value="#!/usr/bin/gawk" />
      <match offset="0" type="string" value="#! /usr/bin/gawk" />
      <match offset="0" type="string" value="#!/usr/local/bin/gawk" />
      <match offset="0" type="string" value="#! /usr/local/bin/gawk" />
      <match offset="0" type="string" value="#!/bin/awk" />
      <match offset="0" type="string" value="#! /bin/awk" />
      <match offset="0" type="string" value="#!/usr/bin/awk" />
      <match offset="0" type="string" value="#! /usr/bin/awk" />
    </magic>
  </mime-type>
  <mime-type type="application/x-bcpio">
    <comment>BCPIO document</comment>
    <comment xml:lang="az">BCPIO sənədi</comment>
    <comment xml:lang="cy">Dogfen BCPIO</comment>
    <comment xml:lang="fi">BCPIO-asiakirja</comment>
    <comment xml:lang="fr">document BCPIO</comment>
    <comment xml:lang="hu">BCPIO-dokumentum</comment>
    <comment xml:lang="nl">BCPIO document</comment>
    <comment xml:lang="nn">BCPIO-dokument</comment>
    <comment xml:lang="no">BCPIO-dokument</comment>
    <comment xml:lang="sr">BCPIO документ</comment>
    <comment xml:lang="sv">BCPIO-dokument</comment>
    <glob pattern="*.bcpio" />
  </mime-type>
  <mime-type type="application/x-bittorrent">
    <comment>BitTorrent seed file</comment>
    <comment xml:lang="az">BitTorrent seed faylı</comment>
    <comment xml:lang="cy">Ffeil hadu BitTorrent</comment>
    <comment xml:lang="fi">BitTorrent-siementiedosto</comment>